version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/etc/mysql/:/etc/mysql/conf.d/
      - ./db_data/:/var/lib/mysql/
      - ./init-sql/:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yearning
      MYSQL_DATABASE: Yearning
      MYSQL_USER: yearning
      MYSQL_PASSWORD: yearning
  yearning:
    image: registry.cn-hangzhou.aliyuncs.com/cookie/yearning:latest
    depends_on:
      - db
    ports:
      - "9180:8000"
    environment:
      HOST: localhost
      MYSQL_PASSWORD: yearning
      MYSQL_USER: root
      MYSQL_ADDR: db
  inception:
    image: hhyo/inception:latest
    depends_on:
      - db
    ports:
      - "6669:6669"
    volumes:
      - ./inc.cnf:/etc/inc.cnf

# 默认账号：admin，默认密码：Yearning_admin
# 感谢 eacdy 张功震 贡献
